---
title: "GTP-2: Language Models are Unsupervised Multitask Learners"
output:
  github_document:
    fig_width: 8
    fig_height: 4
---

## Install

Install package from GitHub,

```{r eval=FALSE}
remotes::install_github("javierluraschi/gpt2")
```

Followed by installing the GPT-2 runtime,

```{r eval=FALSE}
gpt2::install_gpt2()
```

**Note:** Python 3 is required. If Python 2 is installed in your system, you can consider installing MiniConda followed by restarting your R session and ensuring conda is used:

```{r eval=FALSE}
reticulate::use_condaenv("r-gpt2", required = TRUE)
```

## Getting Started

To generate text using GPT-2, specify a `promt` and let the mode run,

```{r eval=FALSE}
gpt2::gpt2("Hello my name is")
```
```
 is Nicolas Eric Malmersky, born in Marietta, Georgia, in December 1957, baptized by a priest in the New Orleans Liturgy. He had never had a sense of the Mother and this was a young brother, Tabernacle. And so he started his life with anticoagulated love and goodness. Then even after a great many hideous decorations that displayed his manly appearance, a righteous incarnation to Christ and to the Supreme Being opened up and some not untouchable soldiers attended to it. During this time he wore headscarves which could not be removed but which had always been put on first, because he never got it off and because such prayer flaming Himself with bitter anticoagulated perversions this the ancient and most special prayer abounding.

He made wife and children with others very many years before he turned to African Christianity. This state moneymodels of which his ancestors call his kop de pimota, yesterday he was a Kirkwood pastors minister, Evangelic priest. As the governor issued this multitudinous charter certain ministers tra mereipalities Altoz con riero Fravilos, although the thoroughness of these shall be considered for all time, and against apostasy. Evangelicals are wont to gather in a sort of garage at the van level-pole Pop. Till he was 18 years old, as a poprist in the .l'La The., he regularly attended open shows in churches. He swore by the Protesene Common Teaching System and by the Universal Council for New Internationalism and by St. Paul and other Gnostics and devout Catholics. Among the men at a national u12mnine press the high priests delivered straight commins urgent callings was from and in the Evening, NEW ZEALAND in 1912 * 64 U include Yeasted topping "Semmeticoestones," such that when Venice obliged Perth Ballistix or the Kirin Mihál maked the glass bottles of Eureka Japanese handwax, the commanders bore on days and deride epun Callecal paper of their idolatry. When Hitler did appear in Wilhelm Mariani's letter fourteen years later, the pride seemingly dwelt in the writer of the name "Nicholas Felinspired."

A Papa Karp is a Bedouin party and feast offered by the Lord. His son Vladanta came from Illuana, Fla., where he needs injuries to put on his armour. He maintained his mixtures till his death during 1969.

Society's tentacle-less traveller everywhere is Richard Olivier (Abd 1081-1133) of 904 duns and in his time frescoed in a churchyard of the palace of the Souchard palace, Amersfoort, in the Third England. A conqueror with great prowess the Fleet of Virginia, Harold Gold avenues party finally settled down in Halifax in the Quchter, Bath, the Sangines of Halifax, overall like those who have arisen from North America but with more of a steely and pale face because their palms only sofully had the physical physical world. While sailing with his crew there was grousing and whining in the ether of leaping vessels. He returned home daggers with claw "Scope." A Wellington Winhole entangle the sheepings.

Much of the text to this Province omits one third of the Greeks probably remaining the largest group on the face of the Earth, could possibly leave little along the way of their learning, which at micromode ed ologies means so as not to draw suspicion on people he does not like to touch. Maurongese might become Normans of the Gray Coast Pantheon, seeing this as pleasant fortune.

Lusa Tristanowni ( English, u.5 V Bugwedorf, Ch. I 33) is the spiritual party leader at the Dumas Stones near Clyde county, "of the supreme Anglaise regularist New England Aghoriation Lodge," chiefly the 63-degree "blugholic Paingones, Conveniently seating around 12-13 Pot Hutchinson volumes."

he half Finnish mane of Burke's, partly Ma Latvialohar Sprfoundtailhustt (Burke WM JUR OVB 1938). Taymok is the birthplace of Maiak, Tartary. It is possible Nils himself came into England from elsewhere but Namhäfn dis Luguh Reikär is known as Lulu (His name credit Mats could have come to Nils as a man from today) because he was the Blithe Breets' business man-leading bookseller. He was himself a the first Beatley and reporter for a small number of publications such as The Suez Hotels Report, U's Lowell Sco. Ltd., The Times Herald-Globe Courier, and The Argus Times. There is SEARCH CONNECTION ASSOCIATED PRESS the sczo tyoot of commercial affairs which this had no place in is actual hard work by
```
